version: 2 

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - '-s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}} -X main.BuiltBy=goreleaser'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

snapcrafts:
  - id: szero
    name: szero
    publish: true
    summary: Temporarily scale down/up/restart all deployments in a namespace
    description: |
      Downscale all deployments in a namespace to 0 replicas and back to their
      previous state. Useful when you need to tear everything down and bring
      it back in a namespace.
      
      **Usage**

      **Downscale all deployments in a namespace to 0 replicas:**

      `szero down -n <namespace> -n <another_namespace>`

      **Upscale all deployments in a namespace to their previous state:**

      `szero up -n <namespace> -n <another_namespace>`

      **Restart all deployments in a namespace**

      `szero restart -n <namespace> -n <another_namespace>`

      **Use a different kubeconfig file**

      `szero down -n <namespace> --kubeconfig <path_to_kubeconfig>`

      **Use a different context**

      `szero down -n <namespace> --context <context_name>`

      **Completions**
      Command line completions are available under the `completions` subcommand.
      For example, to enable bash completions, run:
      `source <(szero completion bash)`
      
      **Using the default kubeconfig file**
      The default kubeconfig file is `$HOME/.kube/config`. In order to use it 
      from the snap package, you need to connect the `dot-kube-config` plug:
      `snap connect szero:dot-kube-config`
    channel_templates:
      - stable
    grade: stable
    confinement: strict
    license: MIT
    base: core22
    plugs:
      dot-kube-config:
        interface: personal-files
        read:
          - $HOME/.kube/config
    apps:
      szero:
        command: szero
        plugs: [ "network", "home", "removable-media", "dot-kube-config" ]
        environment:
          HOME: /home/$USER
