version: 2 

before:
  hooks:
    - go mod tidy
    - go build -o . ./...
    - ./completions.sh
    - ./manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - '-s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}} -X main.BuiltBy=goreleaser'
    main: ./cmd/szero

archives:
  - files:
      - README.md
      - LICENSE
      - completions/*
      - man/*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [ zip ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  -
    name: szero
    homepage: "https://github.com/jadolg/szero"
    description: "Temporarily scale down all deployments, statefulsets, and daemonsets in a namespace."
    commit_author:
      name: jadolg
      email: diazorozcoj@gmail.com
    repository:
      token: "{{ .Env.GORELEASER_TAP_GITHUB_SECRET }}"
      owner: jadolg
      name: homebrew-tap
      pull_request:
        enabled: false
    conflicts:
      - formula: szero
    completions:
      bash: completions/szero.bash
      zsh: completions/szero.zsh
      fish: completions/szero.fish
    manpages:
      - man/szero.1.gz
    hooks:
      post:
        install: |
          on_macos do
            # Remove quarantine attribute if it exists
            if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
              system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/szero"]
            end
          end

nfpms:
  -
    id: szero
    package_name: szero
    homepage: https://github.com/jadolg/szero
    maintainer: Jorge Alberto Díaz Orozco (Akiel) <diazorozcoj@gmail.com>
    description: |-
      Temporarily scale down all deployments, statefulsets, and daemonsets in a namespace
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    section: default
    priority: extra
    contents:
      - src: ./completions/szero.bash
        dst: /usr/share/bash-completion/completions/szero
        file_info:
          mode: 0644
      - src: ./completions/szero.fish
        dst: /usr/share/fish/vendor_completions.d/szero.fish
        file_info:
          mode: 0644
      - src: ./completions/szero.zsh
        dst: /usr/share/zsh/vendor-completions/_szero
        file_info:
          mode: 0644
      - src: man/szero.1.gz
        dst: /usr/share/man/man1/szero.1.gz
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
