version: 2 

before:
  hooks:
    - go mod tidy
    - go build .
    - ./completions.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - '-s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}} -X main.BuiltBy=goreleaser'

archives:
  - files:
      - README.md
      - LICENSE
      - completions/*
      - man/*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  -
    name: szero
    homepage: "https://github.com/jadolg/szero"
    description: "Temporarily scale down/up/restart all deployments in a namespace."
    commit_author:
      name: jadolg
      email: diazorozcoj@gmail.com
    repository:
      token: "{{ .Env.GORELEASER_TAP_GITHUB_SECRET }}"
      owner: jadolg
      name: homebrew-tap
      pull_request:
        enabled: false
    directory: Formula
    install: |
      bin.install "szero"
      bash_completion.install "completions/szero.bash" => "szero"
      zsh_completion.install "completions/szero.zsh" => "_szero"
      fish_completion.install "completions/szero.fish"
      man1.install "man/foo.1.gz"
