apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: szero
spec:
  version: {{ .TagName }}
  homepage: https://github.com/jadolg/szero
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/jadolg/szero/releases/download/{{ .TagName }}/szero_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./szero"
      to: "kubectl-szero"
    - from: LICENSE
      to: "."
    bin: "kubectl-szero"

  - selector:
      matchLabels:
        os: linux
        arch: "386"
    {{addURIAndSha "https://github.com/jadolg/szero/releases/download/{{ .TagName }}/szero_linux_386.tar.gz" .TagName }}
    files:
    - from: "./szero"
      to: "kubectl-szero"
    - from: LICENSE
      to: "."
    bin: "kubectl-szero"

  - selector:
      matchLabels:
        os: linux
        arch: "arm64"
    {{addURIAndSha "https://github.com/jadolg/szero/releases/download/{{ .TagName }}/szero_linux_arm64.tar.gz" .TagName }}
    files:
    - from: "./szero"
      to: "kubectl-szero"
    - from: LICENSE
      to: "."
    bin: "kubectl-szero"

  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/jadolg/szero/releases/download/{{ .TagName }}/szero_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "./szero"
      to: "kubectl-szero"
    - from: LICENSE
      to: "."
    bin: "kubectl-szero"

  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/jadolg/szero/releases/download/{{ .TagName }}/szero_darwin_arm64.tar.gz" .TagName }}
    files:
    - from: "./szero"
      to: "kubectl-szero"
    - from: LICENSE
      to: "."
    bin: "kubectl-szero"

  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/jadolg/szero/releases/download/{{ .TagName }}/szero_windows_amd64.zip" .TagName }}
    files:
    - from: "./szero.exe"
      to: "kubectl-szero.exe"
    - from: LICENSE
      to: "."
    bin: "kubectl-szero.exe"

  - selector:
      matchLabels:
        os: windows
        arch: "386"
    {{addURIAndSha "https://github.com/jadolg/szero/releases/download/{{ .TagName }}/szero_windows_386.zip" .TagName }}
    files:
    - from: "./szero.exe"
      to: "kubectl-szero.exe"
    - from: LICENSE
      to: "."
    bin: "kubectl-szero.exe"

  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/jadolg/szero/releases/download/{{ .TagName }}/szero_windows_arm64.zip" .TagName }}
    files:
    - from: "./szero.exe"
      to: "kubectl-szero.exe"
    - from: LICENSE
      to: "."
    bin: "kubectl-szero.exe"

  shortDescription: Scale all workloads in a namespace to 0 and back
  description: |
    Downscale all deployments, statefulsets, and daemonsets in a namespace to 0 replicas and back to their previous state.
    Useful when you need to tear everything down and bring it back in a namespace.
